### ISSUE TITLE
How to get Easy Set and Hard Set score?

### ISSUE THREAD

**Issue by ShuaibinLi** [qinyiwei/InfoBench#2]

**Comment by KaiQiangSong** [comment]
Hi, the easy and the hard set label is provided in the dataset. You may want to modify the code and group the results with those labels.

> _No description provided._

**Comment by KaiQiangSong** [comment]
> _No description provided._

Hi, the easy and the hard set label is provided in the dataset. You may want to modify the code and group the results with those labels.
